from dotenv import load_dotenv
import os

load_dotenv()  # load variables from .env into environment

CLOUDINARY_CLOUD_NAME = os.getenv("CLOUDINARY_CLOUD_NAME")
CLOUDINARY_API_KEY = os.getenv("CLOUDINARY_API_KEY")
CLOUDINARY_API_SECRET = os.getenv("CLOUDINARY_API_SECRET")

CREDENTIAL_PATH = os.getenv("GOOGLE_APPLICATION_CREDENTIALS")

STUDENT_DATA_PATH = os.getenv("STUDENT_DATA_PATH", "students.csv")

MYSQL_USERNAME=os.getenv("MYSQL_USERNAME")
MYSQL_PASSWORD=os.getenv("MYSQL_PASSWORD")
MYSQL_HOST=os.getenv("MYSQL_HOST")
MYSQL_DATABASE=os.getenv("MYSQL_DATABASE")
ATTENDANCE_ELAPSED_MINUTES = int(os.getenv("ATTENDANCE_ELAPSED_MINUTES", 1))